# Generated by Django 5.2.6 on 2025-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
